services:
  react-vite:
    image: react-job-app-image
    build: .
    container_name: react-job-app-container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
